### ISSUE TITLE
Only works for single tab

### ISSUE THREAD

**Issue by wilkinnh** [yuhua-chen/MCLog#2]
I often work with multiple tabs open, and it looks like the filter bar is only present for a single tab. Can we enable this to work for any open tab? Currently using with Xcode 5.1.1. Thanks!

**Comment by gerchicov-bp** [comment]
It should be reopened. Steps:
1)run app and type something to filter the console (as usual) but don't fully empty the console
2)open another tab (I do it via "cmd+t") and look at console - the field with regex is empty and the console output appears as without filtering
3)copy the regex from the first tab to a new tab and apply it
Expected result - the same console log for 2 tabs.
Actual result the console log on the second tab is totally empty.

To fix the described problem I need to choose "All output" from the dropdown list to the left of the regex textfiled but it is temp solution only.

Additionally it could be better to save some last regexes because an user must input them each time manually.
